#至一千年后的你 BY NANCY QIN秦某南
import time
import datetime
now_str = datetime.datetime.now().strftime('%Y-%m-%d')
now = datetime.datetime.strptime(now_str, "%Y-%m-%d")
future = datetime.datetime.strptime("3020-02-02", "%Y-%m-%d")
days = (future - now).days
print("至一千年后的你 BY NANCY QIN秦某南")
print(days)
print("上面的数字，是本程序消失之前所能在北极保存的最大期限（除非有人愿意接手）,单位为天。")
time.sleep(1)
print("......以上都是我在2020年2月编辑的原文......接下来开始正文（最后编辑时间为2020-10-2，保留此行内容）")
time.sleep(1)
print("现在是2020年5月，‘2019-ncov’已经在国内基本得到控制，可是全球疫情还未结束。")
time.sleep(1)
print("没什么可以说的了.......")
time.sleep(1)
print("也许得一千年之后再见了！")
time.sleep(1)
print("......")
time.sleep(1)
print("......")
time.sleep(1)
print("以上文字都是我在2020年5月及以前编辑的。")
time.sleep(1)
print("实际上，当你们看到这段文字时，已经是2025年02月02日了。")
time.sleep(1)
print("现在是2020-10-02，‘2019-ncov’......，不，'COVID-19'疫情在国内反弹了几次，不过现在已经几乎控制住了。")
time.sleep(1)
print("但在国外,'COVID-19'疫情仍然十分严峻。")
time.sleep(1)
print("现在，我已经放弃了PYTHON，回归了SCRATCH编程，但这个程序还会继续更新的:D")
time.sleep(1)
print("也许得一千年之后再见了！(梅开二度）")
time.sleep(10)
print("Github的编辑器貌似出BUG了......用个TIME模块都能缩进......")
